In [15]:
## Notebook to collect data
## Forming template
## Get social economic data
def get_url(state_id):
    ## Total population, black, white, hispanic, asian, income
    
    s1_t = "https://api.census.gov/data/2018/acs/acs5?get=B02001_001E,B02001_003E,B02001_002E,B03001_003E,B02001_005E,B25105_001E&for=county:*&in=state:"
    
    s_state = str(state_id)
    if (len(s_state)==1):
        s_state = "0"+s_state
    return [s1_t+s_state]
state_id = [1,2,4,5,6,8,9,10,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56,72]

In [17]:
import csv
from urllib.request import urlopen
for i in range(0, len(state_id)):
    state_url = get_url(state_id[i])
    curr_id = state_id[i]
    head_rt = []
    data_rt = []

    link = state_url[0]
    ## print(link)
    f = urlopen(link)
    myfile = f.read()
    myfile = str(myfile)
    data = myfile.split("\\n")
    head = data[0].split(",")
    head[0] = head[0][4:]
    head = head[:-1]
    print(head)
    head[-1]=head[-1][:-1]
    data = data[1:]
    data_arr = []
    for i in range(0, len(data)):
        curr_arr = data[i].split(",")[:-1]
        curr_arr[0]=curr_arr[0][1:]
        curr_arr[-1]=curr_arr[-1][:-1]
        for j in range(0, len(curr_arr)):
            curr_arr[j]=curr_arr[j]
        data_arr.append(curr_arr)
    head_rt = head[-3:]+head[:-3]
    for i in range(0,len(data_arr)):
        curr_arr = data_arr[i]
        data_rt.append(curr_arr[-3:]+curr_arr[:-3])
    link = state_url[0]
    ## print(link)
    f = urlopen(link)
    myfile = f.read()
    myfile = str(myfile)
    data = myfile.split("\\n")
    head = data[0].split(",")
    head[0] = head[0][4:]
    head = head[:-1]
    head[-1]=head[-1][:-1]
    data = data[1:]
    data_arr = []
    for i in range(0, len(data)):
        curr_arr = data[i].split(",")[:-1]
        curr_arr[0]=curr_arr[0][1:]
        curr_arr[-1]=curr_arr[-1][:-1]
        for j in range(0, len(curr_arr)):
            curr_arr[j]=curr_arr[j]
        data_arr.append(curr_arr)
    head_rt = head_rt+head[:-3]
    for i in range(0,len(data_arr)):
        #print(len(curr_arr))
        curr_arr = data_arr[i]
        data_rt[i]=data_rt[i]+curr_arr[:-3]
    for i in range(0,len(data_rt)):
        for j in range(0,len(data_rt[i])):
            #print(str(i)+" "+str(j))
            if (data_rt[i][j]!="null"):
                data_rt[i][j]=data_rt[i][j][1:-1]
    filename = "rt/data_state_"+str(curr_id)+".csv"
    print(filename)
    final_rt = []
    final_rt.append(head_rt)
    for i in range(0, len(data_rt)):
        final_rt.append(data_rt[i])
    with open(filename,"w+") as my_csv:
        csvWriter = csv.writer(my_csv)
        csvWriter.writerows(final_rt)

['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_1.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_2.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_4.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_5.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_6.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_8.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_9.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_10.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_12.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_13.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_15.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_16.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_17.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_18.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_19.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_20.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_21.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_22.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_23.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_24.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_25.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_26.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_27.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_28.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_29.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_30.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_31.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_32.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_33.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_34.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_35.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_36.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_37.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_38.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_39.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_40.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_41.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_42.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_44.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_45.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_46.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_47.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_48.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_49.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_50.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_51.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_53.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_54.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_55.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_56.csv
['"B02001_001E"', '"B02001_003E"', '"B02001_002E"', '"B03001_003E"', '"B02001_005E"', '"B25105_001E"', '"state"', '"county"]']
rt/data_state_72.csv

In [43]:
## Read csv file
import pandas as pd
df = pd.DataFrame(columns=['state', 'county', 'pop', 'black', 'white', 'asian', 'hispanic', 'income'])

In [42]:
df

Empty DataFrame
Columns: [state, county, pop, black, white, asian, hispanic, income]
Index: []

In [48]:
state_code = [1,2,4,5,6,8,9,10,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56,72]
for code in state_code:
    print(code)
    filepath = "rt/data_state_"+str(code)+".csv"

    state = pd.read_csv(filepath)


    pop = state['"B02001_001E"'][:-1]
    black = state['"B02001_003E"'][:-1]
    white = state['"B02001_002E"'][:-1]
    asian = state['"B02001_005E"'][:-1]
    hispanic = state['"B03001_003E"'][:-1]
    income = state['"B25105_001E"'][:-1]
    state_id = state['"state"'][:-1]
    county = state['"county"'][:-1]

    temp= pd.DataFrame(columns=['state', 'county', 'pop', 'black', 'white', 'asian', 'hispanic', 'income'])
    temp['state']=state_id
    temp['county']=county
    temp['pop'] = pop
    temp['black'] = black/pop
    temp['white'] = white/pop
    temp['asian'] = asian/pop
    temp['hispanic'] = hispanic/pop
    temp['income'] = income

    df=df.append(temp)

1
2
4
5
6
8
9
10
12
13
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
44
45
46
47
48
49
50
51
53
54
55
56
72

In [49]:
df

   state county     pop     black     white     asian  hispanic income
0      1    115   87306  0.094518  0.873067  0.008442  0.023927    779
1      1     43   82313  0.012124  0.952365  0.004058  0.043043    671
2      1     69  104352  0.269070  0.693681  0.008366  0.032937    736
3      1    125  206213  0.316469  0.644368  0.016013  0.036065    891
4      1     31   51288  0.172146  0.758910  0.012985  0.069197    739
..   ...    ...     ...       ...       ...       ...       ...    ...
72    72     47   34165  0.064920  0.796371  0.000000  0.989639    230
73    72     95   11023  0.729293  0.254649  0.000000  0.988479    197
74    72    113  143926  0.054431  0.773856  0.000660  0.993483    272
75    72    131   37964  0.028738  0.702718  0.002766  0.977953    222
76    72    137   79726  0.108359  0.674084  0.000000  0.990041    481

[3168 rows x 8 columns]